[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.17.1", features = ["derive"] }
cgmath = "0.18.0"
env_logger = "0.11.5"
log = "0.4.22"
pollster = "0.3.0"
wgpu = "22.1.0"
winit = "0.30.5"
